### ISSUE TITLE
[ Pledge Workflow Part 2 ] Build modals

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#1015]
Please create a branch against the **[`pledge-workflow` branch](https://github.com/mozilla/teach.webmaker.org/tree/pledge-workflow)**, not `develop`.  :+1: ヽ( ^ω^ ゞ )

---
Depends on [[ Pledge Workflow Part 1 ] Rearrange CTA buttons on Homepage](https://github.com/mozilla/teach.webmaker.org/issues/1014)
 - [ ] Implement modal pledge (design see #908)
 - [ ] Implement Success modal including Twitter and Facebook sharing functionality (design see #908)
 -  [ ] ~~Load FontAwesome (pending @sabrinang 's decision on https://github.com/mozilla/teach.webmaker.org/issues/939)~~ (created a separate issue for this task https://github.com/mozilla/teach.webmaker.org/issues/1035)

---

meta bug for Pledge Workflow: https://github.com/mozilla/teach.webmaker.org/issues/978

**Comment by mmmavis** [comment]
waiting for image files to come :wink:

**Comment by mmmavis** [comment]
@toolness have you started working on this ticket?  If not I think I'll tackle this later today.

**Comment by toolness** [comment]
Sure, go right ahead--you might want to keep an eye on #1034 just to be aware of the a11y fixes I'm making there, so you know what roadblocks might face the users of this new pledge modal.

oy making modals accessible is :sob: HARD :sob: !

**Comment by mmmavis** [comment]
:question: :question: :question:   @sabrinang so 


![1st Modal](https://cloud.githubusercontent.com/assets/2492510/8044040/cd3ce344-0dde-11e5-98c5-09f6cc4f6af3.png)
(from https://github.com/mozilla/teach.webmaker.org/issues/908#issuecomment-110122037)

and

![2nd Modal](https://cloud.githubusercontent.com/assets/2492510/7923225/47f9eeac-0866-11e5-8dcd-2661f991c65d.png)
(from https://github.com/mozilla/teach.webmaker.org/issues/908#issuecomment-107710431)

are the 2 mockups I should refer to?

**Comment by sabrinang** [comment]
@mmmavis Yes those are the 3 modals

**Comment by mmmavis** [comment]
waiiiit, 3???

**Comment by sabrinang** [comment]
oops 2

**Comment by mmmavis** [comment]
Just a reminder that we should *always* include the privacy policy checkbox in a form like this. :wink: 

also @sabrinang , I noticed that we have 2 types of buttons in modal:

the **flat and full-width** one seen in the Add You Club modal dialog
![screen shot 2015-06-16 at 10 00 29 pm](https://cloud.githubusercontent.com/assets/2896608/8199994/2f4af4aa-1473-11e5-82bf-c037d1530ddd.png)

and the one you have on your mockup above

:question: Question: which style should we go with?

**Comment by sabrinang** [comment]
I got the R+ to go with the non-full width button that looks similar to the other CTA buttons on the teach site (all caps, rounded corners and depth) so we should go with the mockup style to unify with existing CTA buttons

**Comment by mmmavis** [comment]
@sabrinang do we plan to fix the button styling on the Add Your Club modal?  Or we are good to keep it as is?

**Comment by mmmavis** [comment]
@hannahkane need copy that goes to the "sharing on social media" functionality.  :eyes:

**Comment by hannahkane** [comment]
@mmmavis - "I just pledged to #TeachTheWeb! https://teach.mozilla.org"
