### ISSUE TITLE
Teach site v1 release

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#152]
### Release checklist ###

Product:
 - [x] Thorough site review: copy, links, workflows (#63)
 - [x] Plan for conducting user tests (started a separate thread with @iamjessklein and @adamlofting about this)

Technical:
- [ ] domain ready
- [ ] SSL cert secured and in place
- [x] Google Analytics in place, tested, right people have access
- [x] Terms of Service & Privacy Policy in place (#267)
- [x] Localization approach is set (in particular, we know how to deal w/
localization requests)
- [x] Confidence that we can deal with load in case a site is deemed likely
to be very popular
- [x] Heads-up to MoFo and MoCo Comms team
- [x] Security sign-off from dev team (#680)
- [ ] Production configuration sign-off from dev-team (i.e. we're not
shipping un-optimized pages)

Post-Release tasks:
 - [ ] Make sure all previously published links properly redirect (#266) 
 - [ ] Remove Teach tab from Webmaker.org (https://github.com/mozilla/webmaker.org/issues/1377) 
 - [ ] Add a referral to new site from Webmaker.org (https://github.com/mozilla/webmaker.org/issues/1377) 
 - [ ] Update to the sitemap esp. if it's under the mozilla.org domain
hierarchy (because we may want the site to show up (or not) in that site's
sitemap)
 - [ ] Draft email to send to Club leaders; CTA: Add Your Club to the map

**Comment by hannahkane** [comment]
I don't know if we have a standard release checklist somewhere, so please let me know if we do. I think it would be useful to think through all of the necessary tasks we'll need to complete before and immediately following the release of v1.

I couldn't think of very many! I'm sure there are lots more, especially on the technical side. Hoping others can help me populate this checklist.

In terms of promoting the new site, I need some guidance from others. My sense is we're not going big, but maybe there are some small things we want to do.

/cc @chrislarry33 @davidascher @simonwex @cassiemc @ldecoursy @adamlofting @HPaulJohnson

**Comment by chrislarry33** [comment]
Yes, softest of soft launches for two weeks at least. We will share with most active communities and partners for feedback and to find any issues. I'd rather talk about this more loudly when we have a broader story to tell then just a website.

**Comment by davidascher** [comment]
release checklist includes:

- [ ] domain ready
- [ ] SSL cert secured and in place
- [ ] Google Analytics in place, tested, right people have access
- [ ] Terms of Service & Privacy Policy in place
- [ ] Localization approach is set (in particular, we know how to deal w/
localization requests)
- [ ] Confidence that we can deal with load in case a site is deemed likely
to be very popular
- [ ] Heads-up to MoFo and MoCo Comms team
- [ ] Security sign-off from dev team
- [ ] Production configuration sign-off from dev-team (i.e. we're not
shipping un-optimized pages)
- [ ] Update to the sitemap esp. if it's under the mozilla.org domain
hierarchy (because we may want the site to show up (or not) in that site's
sitemap)

but we should build a bigger list in a more stable place, with help from
other TPS folks.

**Comment by hannahkane** [comment]
woohoo! This is great. I will start making sure that we're checking these boxes, and will bring this up at the next TPS meeting, too.

**Comment by hannahkane** [comment]
Some updates:
 * added specific tickets for several items on this list (see ticket description above)
 * @HPaulJohnson has filed the request for the domain in a bugzilla ticket
 * GA is on track (@adamlofting, please correct me if I'm wrong)
 * Filed a ticket with data practices team
 * Our l10n strategy is to NOT localize until we've had a change to validate the site with an EN-reading audience. We'll capture interest in localisation so we can follow up when we're ready.
 * I do not think there's any reason to be concerned about load; the site will not be publicized widely.
 * Mofo comms is in the loop, but I'm not sure about Moco comms. @HPaulJohnson - are there things we need to do to adequately prep Moco comms for this launch? (We don't have any needs from them.)

And some questions, likely for @davidascher :
 * what's the process for the SSL cert?
 * Are the security and production sign-offs from the Mofo or Moco dev team?

**Comment by davidascher** [comment]
SSL cert: @jdotpz or delegate via @simonwex
Security review @pomax as per @simonwex

**Comment by jdotpz** [comment]
@mmmavis let me know which domain name we are using for this (ala teach.webmaker.org) and I can get the SSL cert.

**Comment by iamjessklein** [comment]
@jdotpz - this will be teach.mozilla.org 
cc/ @hannahkane

**Comment by jdotpz** [comment]
SSL cert request submitted in Digicert.

**Comment by hannahkane** [comment]
awesome. thanks, @jdotpz!

**Comment by iamjessklein** [comment]
:+1:  :tada: :balloon:

**Comment by hannahkane** [comment]
Hey @jdotpz - is there any update on the SSL cert?

**Comment by jdotpz** [comment]
It's still being processed over on MoCo side, I'll send out some pings today and ask about moving that right along.

**Comment by hannahkane** [comment]
@jdotpz - any word on the SSL cert?
@HPaulJohnson - any word on the domain?
@simonwex - how long should we plan for the security review? Can that start now?

**Comment by HPaulJohnson** [comment]
@hannahkane no update yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1143719 but sounds like @jdotpz will push forward when we have code ready.

**Comment by simonwex** [comment]
@hannahkane we can start the sec review process. @toolness we should jam on that a bit. Let's talk about it tomorrow during our 1:1.

**Comment by jdotpz** [comment]
Do we have code ready for this?

**Comment by hannahkane** [comment]
@jdotpz - We have not completely finished the site yet, if that's the question. I just wanted to confirm that when we are code complete (likely early next week), we'll be able to move it to production on teach.mozilla.org.

**Comment by toolness** [comment]
Oh, it should be noted that the "site" actually involves two completely different deploys: 

* **teach.mozilla.org** is a totally static site deployable to S3.
* The [backend REST API](https://github.com/mozilla/teach-api), which the static site communicates with, is a Django app that can be deployed at whatever domain we want (the user will never see it, though teach staff will access its django-admin UI).

It should also be noted that, in the future, we might need to make the static site a very lightweight node app that renders pages dynamically on the server-side, to support features like mentor profiles in an accessible way.

**Comment by jdotpz** [comment]
SSL is all ready to rock.  @jbuck want to deploy this, or want me to set it up somewhere?  Perhaps @simonwex has thoughts on where it should go?

**Comment by simonwex** [comment]
@toolness what do you think about teach.mozilla.org onto S3 and chucking the django app on Heroku?

**Comment by jdotpz** [comment]
teach. will need to go on Cloudfront if you want SSL.

**Comment by toolness** [comment]
I am cool w/ that @simonwex!

**Comment by jbuck** [comment]
@jdotpz yeah, if you could let me take it that'd be lovely . I think the deployment plan makes sense

**Comment by hannahkane** [comment]
Assigning this to @simonwex, who I think will make the ultimate call about when to release the site. I can make a call about whether all of the product reqs have been met, but it'll be @simonwex who makes a technical call. (Does that seem right?)

**Comment by simonwex** [comment]
@hannahkane wfm

**Comment by rossbruniges** [comment]
Really looking forward to seeing this live!

Good work all!

**Comment by iamjessklein** [comment]
Thanks @rossbruniges :+1:  We are in QA-ing mode, so please feel free to check out the [staging site](http://teach.mofostaging.net/) and file issues :bug: :beetle: :bee:

**Comment by toolness** [comment]
Thanks @rossbruniges! The site isn't yet as progressively-enhancey as we'd like it to be, e.g. #455, but we'll be working to make that better in v2 :) Would love any of your thoughts on this stuff.

**Comment by jgmac1106** [comment]
I am now going to strive to be progressively-enhancey in all my teaching
and webby stuff

**Comment by hannahkane** [comment]
We are getting super close to the product being ready for deployment. @simonwex - what do we need to do to check off the last few boxes in the description above?

**Comment by hannahkane** [comment]
@jdotpz - we're good on the domain and the SSL cert, right? Can I check those boxes off in the main ticket description?

**Comment by secretrobotron** [comment]
ping! staging is looking good now. Should be able to start getting a prod setup online.
@jdotpz @jbuck ?

**Comment by hannahkane** [comment]
@simonwex - have you been able to do the security review? And what about the "Production configuration sign-off" - is that something we still need to do?

**Comment by jbuck** [comment]
SSL cert has been obtained, I still need to setup DNS but I'll have that done today
