### ISSUE TITLE
Reorganize code

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#233]
Today @alicoding, @gesa, @mmmavis, @vazquez and I discussed a folder structure to better represent the structure of the site, and make it easier for new developers to contribute to it.

It roughly looks like this:

```
components/
  Input.jsx
  Form.jsx
  Homepage.jsx
less/
  common.less
  components/
    Input.less
    Form.less
    Homepage.less
mixins/
  funky-react-mixin.js
lib/
  gulp-index-file-stream.js
  index-static.jsx
  routes.jsx
```

Things left to do:
  - [x] Create the folders and move the JS *but not the less* (#238)
  - [ ] Refactor the LESS (#226)
  - [X] ~~Get rid of the `vendor` directory and delegate to npm for that~~ Filed as #246, we'll get to it later

**Comment by gesa** [comment]
@toolness if I remember correctly, you were going to handle the js rearranging, and once that landed I was going to do the Less. Is that correct? (related—is there an issue for moving the js yet? I'd like to reference it in #226)

**Comment by toolness** [comment]
@gesa - yep, just added the WIP PR as #238!

**Comment by toolness** [comment]
Ok, so I've gotten rid of the `pages` directory now for reasons mentioned in the commit log of e931c09aeb29dcbf703d5b11e9b3554ae65f444d:

> * I suspect that the distinction between 'pages' and 'components' will
>  become blurry as the site evolves and becomes more dynamic. In fact,
>  in some sense the distinction already *is* blurry. If things do
>  become too complicated in the future, though, we can always go back
>  to using the 'pages' directory.
>
> * Pages use lots of components, and having to start every component's
>  `require()` with `../components/` was getting quite tedious.

**Comment by toolness** [comment]
Ok, so as per a discussion in https://github.com/mozilla/teach.webmaker.org/pull/238#issuecomment-78269006, we've decided to **not** put components in their own directories with `index.jsx` files and LESS code in them, because we ran into technical difficulties.

Instead, we'll just have `.jsx` files in the `components` directory, and put LESS for the components in a parallel structure at `less/components/`. I've changed the layout in this issue's description to reflect this.

Does that sound reasonable @gesa?

**Comment by gesa** [comment]
sounds great to me @toolness

**Comment by hannahkane** [comment]
do we need to move this to the March 27 heartbeat?

**Comment by toolness** [comment]
actually i think it can be marked as complete now...
