### ISSUE TITLE
Scope Q2 testing process

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#285]
We need to: 

- [x] understand testing improvements based on the debriefs #284 
- [x] establish which club curriculum module(s) will be tested #26 
- [x] scope which leadership curriculum module(s) will be produced #27 
- [x] determine the recruitment process for testers in 200 cities #172 & __
- [x] determine the communication and support process for testers in 200 cities #20 & __

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/89"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/89.
Please don't comment on it here.
