### ISSUE TITLE
File issues for modals

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#295]
In #269 I added a [list of bugs](https://github.com/mozilla/teach.webmaker.org/pull/269#issuecomment-81800754) to file after the PR landed, but this hasn't been done yet... @mmmavis would you mind filing these real quick?

**Comment by mmmavis** [comment]
Tickets filed :hamster: 

- [ ] Modal Dialog - Allow ESC to close a modal https://github.com/mozilla/teach.webmaker.org/issues/299
- [ ] Modal Dialog - Allow clicking outside a modal to close it https://github.com/mozilla/teach.webmaker.org/issues/300
- [ ] Modal Dialog - Ensure that modals have proper accessibility markup https://github.com/mozilla/teach.webmaker.org/issues/301
- [ ] Modal Dialog - Hook the modal's submit button up to the Teach API so it actually submits data https://github.com/mozilla/teach.webmaker.org/issues/302
- [ ] Modal Dialog - The modal's form fields should be validated https://github.com/mozilla/teach.webmaker.org/issues/303
- [ ] Modal Dialog - Add unit tests for the modal https://github.com/mozilla/teach.webmaker.org/issues/304

**Comment by toolness** [comment]
Thanks Mavis!
