### ISSUE TITLE
Build Clubs page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#44]
### RACI
* Phase: Build
* Owner: @hannahkane 
* Decision Maker: @hannahkane 
* Design Lead: NA
* Dev Lead: 
* Quality: @davidascher 

Design assets will come from: #6 

### Requirements
* Responsive
* Works in all supported browser versions

### Tasks:
 - [x] #186 - static HTML/CSS 
 - [x] #185 - Add Mapbox component
 - [ ] Add server-side component(for storing clubs data)
 - [ ] Design review
 - [ ] Content review

---

Edit by @vazquez
InVision Prototype: http://invis.io/VK2CZH0ZC

**Comment by vazquez** [comment]
Background image asset (1x and 2x) available here: https://dl.dropboxusercontent.com/u/43783651/Mozilla/Background%20Image-assets.zip

**Comment by mmmavis** [comment]
@vazquez could you please link me to the Sketch file? :wink:

**Comment by vazquez** [comment]
@mmmavis It is here! https://dl.dropboxusercontent.com/u/43783651/Mozilla/Clubs%20Page.sketch

We can talk through it on Vidyo, that would be no problem.

**Comment by vazquez** [comment]
Design review done! PR is in #265
