### ISSUE TITLE
[MIGRATED] [META] Produce "Your First Month as a Regional Coordinator" Guide [TLM]

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#755]
***Learning outcome for this content***: Have a set of activities remixed to your specific topic area, location and learner interests that embed web literacy.

- [x] Produce TLM "Finding your Crew" module #751
- [x] Produce TLM "Reflecting Openly" module #752 
- [ ] Template an etherpad and discourse thread for coordinating clubs #802 
- [x] Produce TLM "Open Tools" module #753
- [ ] Produce Recruitment template #731 
- [x] Produce TLM "Sharing and Storytelling" module #754
- [ ] Produce TLM "Remixing for Context" module #757
- [ ] Produce Case Studies documentation  (i.e. Rio LAN houses, Chicago public schools)#756
- [x] Design scalable solution for Web Lit Curriculum on Teach site #457
- [ ] Template a letter from the future #837 

***Content Folder*** https://drive.google.com/drive/u/1/#folders/0B0u8434q8_LPNTJlejh4YWhWRkk/0B0u8434q8_LPfkVzUlRuMVZ4MmxIb0dKc01ueEs3MW9uREFUb2RYdWJKeEFTcGRYX2ppM1U

**Comment by thornet** [comment]
Adding the May 8 milestone since we'll have the RC kickoff call on May 5.

**Comment by thornet** [comment]
Latest version: https://docs.google.com/document/d/1f7r94MfAXyaNgLoFWINjenx6MQYVJTSjCqMzTJTFqBY/edit#

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/143"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/143.
Please don't comment on it here.
