### ISSUE TITLE
[MIGRATED] [META] Produce "Your First Month as a Club Captain" Guide [TLM]

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#758]
***Depends on #755 ***

Includes: 
- [ ] TLM Working Openly #752 
- [ ] TLM Open Tools #753 
- [ ] TLM Remixing for Context #757 
- [ ] Clubs Curriculum User Guide including first 16hr of curriculum
- [ ] TLM Sharing/Storytelling #754 
- [ ] TLM Facilitating #763 
- [ ] Case Studies of real-life Club Captains #756 
- [ ] TLM Finding Cohesion & Collaboration #765 

Have updated this issue based on the April 21st Club Call. There may be other TLM modules (e.g. Making is Learning #760 or #761 ) that are part of this pathway

**Comment by ldecoursy** [comment]
Not sure where this might fit best, but worth checking out Open Science handbook if you haven't yet to see where some of this might inform process of starting a club... http://mozillascience.github.io/studyGroupHandbook/

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/146"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/146.
Please don't comment on it here.
