### ISSUE TITLE
Implement Pledge workflow on homepage

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#978]
:exclamation: For each of tasks below, please create a branch against the **[`pledge-workflow` branch](https://github.com/mozilla/teach.webmaker.org/tree/pledge-workflow)**, not `develop`.  :+1: ヽ( ^ω^ ゞ )

----

Includes:

**Rearrange CTA buttons on Homepage #1014**
 - [x] Replace the "Host an Event" CTA with the "Pledge to Teach" CTA. See button icon design in #908 
 - [x] Re-order the CTAs. The left-most should be pledge, the middle should be teach, and the right should be clubs.

**Build modals #1015**
 - [ ] Implement modal pledge (see #908)
 - [ ] Implement Success modal including Twitter and Facebook sharing functionality (see #908)

**Form submission and BSD list #1016**
 - [ ] Upon submission, the user's email address should go into a BSD list (needs to be created, I think. @amirad, is that true?)
 - [ ] Should trigger transactional email (see copy in #957)

**Comment by mmmavis** [comment]
@toolness this is [the share page](https://sendto.mozilla.org/page/content/FCCvote-net-neutrality-share/) that we had for the FCC petition page.  

**Facebook**
https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fmzl.la%2F169Y0wn (replace the `u` query value with the url we want to share)
I think for Facebook we are only allowed to set the url for users - we can't prefill the share message.  Also, we should make sure this is open within a restrained size of popup.  Otherwise the Facebook page will look ugly since the textarea spans 100% of the window width.

**Twitter**
(docs) https://dev.twitter.com/web/intents

**Comment by mmmavis** [comment]
oohhhh and I just found this: http://www.sharelinkgenerator.com/

**Comment by mmmavis** [comment]
If we wanna [do more things with Facebook share](https://developers.facebook.com/docs/plugins/share-button) it seems like we have to use their SDK...

**Comment by hannahkane** [comment]
email doesn't need a fancy template; can be sent through BSD

**Comment by hannahkane** [comment]
@amirad - just want to confirm that we need a new BSD list to capture these emails?

**Comment by amirad** [comment]
No no no, I would love for them to be added to already existing mentor group in bsd

**Comment by mmmavis** [comment]
I just created the base branch `pledge-workflow` and updated the description of this ticket with the following notes

> :exclamation: For each of tasks below, please create a branch against of the **[`pledge-workflow` branch](https://github.com/mozilla/teach.webmaker.org/tree/pledge-workflow)**, not `develop`.  :+1: ヽ( ^ω^ ゞ )

**Comment by mmmavis** [comment]
Hi @amirad what's the name of the BSD group/list we should be adding people to?

**Comment by mmmavis** [comment]
FYI, @hannahkane @toolness I split the todos into 3 sections and I updated [the description of this ticket](https://github.com/mozilla/teach.webmaker.org/issues/978#issue-83747185)

**Comment by amirad** [comment]
@mmmavis it's a sign-up form called "Mentor Signup Form"

**Comment by mmmavis** [comment]
Hey @amirad sorry we can't just repurpose the existing "Mentor Signup Form" BSD form :disappointed: ... since we are triggering a different transaction email as well as the redirect destination will be different from what's set on the current "Mentor Signup Form" BSD form :no_mouth: 
I'll clone a new signup form for this Pledge workflow to use.  More updates on https://github.com/mozilla/teach.webmaker.org/issues/1016 soon

**Comment by amirad** [comment]
Ok no worries. We can change the mentor email/redirect but if it's too much trouble we can create a new form and ask Adam about migrating over the email addresses from the mentor signup.

**Comment by mmmavis** [comment]
@amirad 
If we can make the following changes to the **existing** "Mentor Signup Form" on BSD

1. Page redirect for showing the Thank You message. (Do we ever [this page](https://sendto.mozilla.org/page/s/mentor-signup) directly? If yes, changing the Thank You message destination means that people will be redirected to [the Teach site](https://cloud.githubusercontent.com/assets/2492510/7923225/47f9eeac-0866-11e5-8dcd-2661f991c65d.png) after signing up.)
2. The following fields(see screencap) for the transaction email
![screen shot 2015-06-17 at 5 09 30 pm](https://cloud.githubusercontent.com/assets/2896608/8221455/b1716b94-1513-11e5-9d14-26a0d5537a81.png)


then I think we can use the same form without cloning a new one.

Let me know! :smile:

**Comment by amirad** [comment]
Change it all @mmmavis, change it all :)

**Comment by mmmavis** [comment]
okie dokie!

**Comment by mmmavis** [comment]
yayyyy up on https://teach.mozilla.org/ :tada: :dancers:
